export const criticalTypeFlagList = [
    {
        id: 1,
        type: 'Critical'
    },
    {
        id: 2,
        type: 'Not Critical'
    },
    {
        id: 3,
        type: 'Not Applicable'
    }
];

export const gradeTypeList = [
    {
        id: 1,
        type: 'A'
    },
    {
        id: 2,
        type: 'B'
    },
    {
        id: 3,
        type: 'C'
    },
    {
        id: 4,
        type: 'N'
    },
    {
        id: 5,
        type: 'P'
    },
    {
        id: 6,
        type: 'Z'
    }
];

export const boroTypeList = [
    {
        id: 1,
        type: '0'
    },
    {
        id: 2,
        type: 'Bronx'
    },
    {
        id: 3,
        type: 'Brooklyn'
    },
    {
        id: 4,
        type: 'Queens'
    },
    {
        id: 5,
        type: 'Manhattan'
    },
    {
        id: 6,
        type: 'Staten Island'
    },
];

export const cuisineTypeList = [
    { id: 1, type: 'Afghan' },
    { id: 2, type: 'African' },
    { id: 3, type: 'American' },
    { id: 4, type: 'Armenian' },
    { id: 5, type: 'Asian/Asian Fusion' },
    { id: 6, type: 'Australian' },
    { id: 7, type: 'Bagels/Pretzels' },
    { id: 8, type: 'Bakery Products/Desserts' },
    { id: 9, type: 'Bangladeshi' },
    { id: 10, type: 'Barbecue' },
    { id: 11, type: 'Basque' },
    { id: 12, type: 'Bottled Beverages' },
    { id: 13, type: 'Brazilian' },
    { id: 14, type: 'Cajun' },
    { id: 15, type: 'Californian' },
    { id: 16, type: 'Caribbean' },
    { id: 17, type: 'Chicken' },
    { id: 18, type: 'Chilean' },
    { id: 19, type: 'Chimichurri' },
    { id: 20, type: 'Chinese' },
    { id: 21, type: 'Chinese/Cuban' },
    { id: 22, type: 'Chinese/Japanese' },
    { id: 23, type: 'Coffee/Tea' },
    { id: 24, type: 'Continental' },
    { id: 25, type: 'Creole' },
    { id: 26, type: 'Creole/Cajun' },
    { id: 27, type: 'Czech' },
    { id: 28, type: 'Donuts' },
    { id: 29, type: 'Eastern European' },
    { id: 30, type: 'Egyptian' },
    { id: 31, type: 'English' },
    { id: 32, type: 'Ethiopian' },
    { id: 33, type: 'Filipino' },
    { id: 34, type: 'French' },
    { id: 35, type: 'Frozen Desserts' },
    { id: 36, type: 'Fruits/Vegetables' },
    { id: 37, type: 'Fusion' },
    { id: 38, type: 'German' },
    { id: 39, type: 'Greek' },
    { id: 40, type: 'Hamburgers' },
    { id: 41, type: 'Haute Cuisine' },
    { id: 42, type: 'Hawaiian' },
    { id: 43, type: 'Hotdogs' },
    { id: 44, type: 'Hotdogs/Pretzels' },
    { id: 45, type: 'Indian' },
    { id: 46, type: 'Indonesian' },
    { id: 47, type: 'Iranian' },
    { id: 48, type: 'Irish' },
    { id: 49, type: 'Italian' },
    { id: 50, type: 'Japanese' },
    { id: 51, type: 'Jewish/Kosher' },
    { id: 52, type: 'Juice, Smoothies, Fruit Salads' },
    { id: 53, type: 'Korean' },
    { id: 54, type: 'Latin American' },
    { id: 55, type: 'Lebanese' },
    { id: 56, type: 'Mediterranean' },
    { id: 57, type: 'Mexican' },
    { id: 58, type: 'Middle Eastern' },
    { id: 59, type: 'Moroccan' },
    { id: 60, type: 'New American' },
    { id: 61, type: 'New French' },
    { id: 62, type: 'Not Listed/Not Applicable' },
    { id: 63, type: 'Nuts/Confectionary' },
    { id: 64, type: 'Other' },
    { id: 65, type: 'Pakistani' },
    { id: 66, type: 'Pancakes/Waffles' },
    { id: 67, type: 'Peruvian' },
    { id: 68, type: 'Pizza' },
    { id: 69, type: 'Polish' },
    { id: 70, type: 'Portuguese' },
    { id: 71, type: 'Russian' },
    { id: 72, type: 'Salads' },
    { id: 73, type: 'Sandwiches' },
    { id: 74, type: 'Sandwiches/Salads/Mixed Buffet' },
    { id: 75, type: 'Scandinavian' },
    { id: 76, type: 'Seafood' },
    { id: 77, type: 'Soul Food' },
    { id: 78, type: 'Soups' },
    { id: 79, type: 'Soups/Salads/Sandwiches' },
    { id: 80, type: 'Southeast Asian' },
    { id: 81, type: 'Southwestern' },
    { id: 82, type: 'Spanish' },
    { id: 83, type: 'Steakhouse' },
    { id: 84, type: 'Tapas' },
    { id: 85, type: 'Tex-Mex' },
    { id: 86, type: 'Thai' },
    { id: 87, type: 'Turkish' },
    { id: 88, type: 'Vegan' },
    { id: 89, type: 'Vegetarian' },
];
  
export const exampleJSON = [
    {
      camis: 50124678,
      dba: "STRAWBERRY HOME",
      boro: "Manhattan",
      building: "34A",
      street: "MOTT ST",
      zipcode: 10013,
      phone: 9293666649,
      cuisine_description: "Juice, Smoothies, Fruit Salads",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.71480025,
      "Longitude": -73.99882764,
      "Community Board": 103,
      "Council District": 1,
      "Census Tract": 2900,
      "BIN": "",
      "BBL": 1,
      "NTA": "MN27",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50142490,
      dba: "ROYAL GARDEN",
      boro: "Brooklyn",
      building: 230,
      street: "KINGS HIGHWAY",
      zipcode: 11223,
      phone: 3473315559,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.60539753,
      "Longitude": -73.98237149,
      "Community Board": 311,
      "Council District": 43,
      "Census Tract": 42800,
      "BIN": 3176590,
      "BBL": 3066470016,
      "NTA": "BK29",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50128411,
      dba: "HOT POT",
      boro: "Queens",
      building: 2007,
      street: "127TH ST",
      zipcode: 11356,
      phone: 9292738588,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.7814488,
      "Longitude": -73.84141335,
      "Community Board": 407,
      "Council District": 19,
      "Census Tract": 91900,
      "BIN": 4099328,
      "BBL": 4041720007,
      "NTA": "QN23",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50140145,
      dba: "CHARTWELLS AT PACE, 2ND FLOOR",
      boro: "Manhattan",
      building: 15,
      street: "BEEKMAN STREET",
      zipcode: 10038,
      phone: 7043285184,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.7110425,
      "Longitude": -74.00629792,
      "Community Board": 101,
      "Council District": 1,
      "Census Tract": 1501,
      "BIN": 1079101,
      "BBL": 1000920030,
      "NTA": "MN25",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50143242,
      dba: "NEW YUE RESTAURANT",
      boro: "Manhattan",
      building: 60,
      street: "BAYARD STREET",
      zipcode: 10013,
      phone: 6466092331,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.71544251,
      "Longitude": -73.99795105,
      "Community Board": 103,
      "Council District": 1,
      "Census Tract": 2900,
      "BIN": 1002420,
      "BBL": 1002010029,
      "NTA": "MN27",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50123747,
      dba: "BLANK STREET COFFEE",
      boro: "Manhattan",
      building: 218,
      street: "1 AVENUE",
      zipcode: 10009,
      phone: 9175103862,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.73074609,
      "Longitude": -73.98298406,
      "Community Board": 103,
      "Council District": 2,
      "Census Tract": 3400,
      "BIN": 1006009,
      "BBL": 1004410001,
      "NTA": "MN22",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50047418,
      dba: "CHEZ MATY ET SOKHNA",
      boro: "Manhattan",
      building: 2249,
      street: "ADAM CLAYTON POWELL JR BOULEVARD",
      zipcode: "",
      phone: 2123685005,
      cuisine_description: "African",
      inspection_date: "05/04/2023",
      action: "Violations were cited in the following area(s).",
      violation_code: "04M",
      violation_description: "Live roaches in facility's food or non-food area.",
      critical_flag: "Critical",
      score: 27,
      grade: "B",
      grade_date: "05/04/2023",
      record_date: "11/25/2023",
      inspection_type: "Cycle Inspection / Re-inspection",
      "Latitude": 0,
      "Longitude": 0,
      "Community Board": "",
      "Council District": "",
      "Census Tract": "",
      "BIN": "",
      "BBL": 1,
      "NTA": "",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50126383,
      dba: "",
      boro: "Staten Island",
      building: 78,
      street: "HOWARD AVENUE",
      zipcode: 10301,
      phone: 6465338067,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.6287804,
      "Longitude": -74.08857343,
      "Community Board": 501,
      "Council District": 49,
      "Census Tract": 3300,
      "BIN": 5015143,
      "BBL": 5005890063,
      "NTA": "SI08",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50143188,
      dba: "CECILY",
      boro: "Brooklyn",
      building: 80,
      street: "FRANKLIN STREET",
      zipcode: 11222,
      phone: 3474144249,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.72727545,
      "Longitude": -73.95713045,
      "Community Board": 301,
      "Council District": 33,
      "Census Tract": 56100,
      "BIN": 3065041,
      "BBL": 3025720003,
      "NTA": "BK76",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50118533,
      dba: "JEFFREY KATZ",
      boro: "Manhattan",
      building: 85,
      street: "W 10TH ST",
      zipcode: 10011,
      phone: 2123393970,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.73452688,
      "Longitude": -73.9980948,
      "Community Board": 102,
      "Council District": 2,
      "Census Tract": 6300,
      "BIN": "",
      "BBL": 1,
      "NTA": "MN23",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50142527,
      dba: "VAN CAFE",
      boro: "Manhattan",
      building: 243,
      street: "GRAND STREET",
      zipcode: 10002,
      phone: 2123341313,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.71831342,
      "Longitude": -73.99440845,
      "Community Board": 103,
      "Council District": 1,
      "Census Tract": 1600,
      "BIN": 1003932,
      "BBL": 1003040018,
      "NTA": "MN27",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50119479,
      dba: "FAMOUS ROTISSERIE AND GRILL",
      boro: "Queens",
      building: 9551,
      street: "ROOSEVELT AVE",
      zipcode: 11372,
      phone: 9293519812,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.74911562,
      "Longitude": -73.86986562,
      "Community Board": 403,
      "Council District": 21,
      "Census Tract": 27300,
      "BIN": 4036675,
      "BBL": 4014840050,
      "NTA": "QN28",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50127603,
      dba: "HIGH TIDE",
      boro: "Brooklyn",
      building: 1,
      street: "WATER STREET",
      zipcode: 11201,
      phone: 2122038079,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.70295918,
      "Longitude": -73.99433761,
      "Community Board": 302,
      "Council District": 33,
      "Census Tract": 2100,
      "BIN": 3395552,
      "BBL": 3000250001,
      "NTA": "BK38",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50136314,
      dba: "BLACK HORSES TAVERN",
      boro: "Brooklyn",
      building: 7507,
      street: "NEW UTRECHT AVENUE",
      zipcode: 11214,
      phone: 9294819833,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.61561223,
      "Longitude": -73.99997839,
      "Community Board": 311,
      "Council District": 43,
      "Census Tract": 26400,
      "BIN": 3160170,
      "BBL": 3062250043,
      "NTA": "BK28",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50125004,
      dba: "SABOR ATLIXCO",
      boro: "Queens",
      building: 4408,
      street: "BROADWAY",
      zipcode: 11103,
      phone: 3474475339,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.75738172,
      "Longitude": -73.91564776,
      "Community Board": 401,
      "Council District": 26,
      "Census Tract": 15900,
      "BIN": 4012370,
      "BBL": 4007070037,
      "NTA": "QN70",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50139331,
      dba: "EL CAMINANTE",
      boro: "Brooklyn",
      building: 894,
      street: "DEKALB AVENUE",
      zipcode: 11221,
      phone: 3477709222,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.69260979,
      "Longitude": -73.94046038,
      "Community Board": 303,
      "Council District": 36,
      "Census Tract": 28100,
      "BIN": 3049700,
      "BBL": 3017820036,
      "NTA": "BK35",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50105936,
      dba: "DUNKIN'",
      boro: "Bronx",
      building: 980,
      street: "EAST  233 STREET",
      zipcode: 10466,
      phone: 9174163773,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.89082641,
      "Longitude": -73.84931827,
      "Community Board": 212,
      "Council District": 11,
      "Census Tract": 42400,
      "BIN": 2064812,
      "BBL": 2048680072,
      "NTA": "BX44",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50104825,
      dba: "WENDY'S",
      boro: "Queens",
      building: 1,
      street: "MAIN TERMINAL",
      zipcode: "",
      phone: 9173282791,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 0,
      "Longitude": 0,
      "Community Board": "",
      "Council District": "",
      "Census Tract": "",
      "BIN": "",
      "BBL": 4,
      "NTA": "",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50144043,
      dba: "",
      boro: "Manhattan",
      building: 200,
      street: "WEST   56 STREET",
      zipcode: 10019,
      phone: 2124538269,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.76492076,
      "Longitude": -73.98075154,
      "Community Board": 105,
      "Council District": 6,
      "Census Tract": 13700,
      "BIN": 1024878,
      "BBL": 1010277501,
      "NTA": "MN17",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50104755,
      dba: "FLIK INTERNATIONAL CORP.",
      boro: "Manhattan",
      building: 599,
      street: "LEXINGTON AVENUE",
      zipcode: 10022,
      phone: 7043285090,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.75826818,
      "Longitude": -73.97105441,
      "Community Board": 106,
      "Council District": 4,
      "Census Tract": 10000,
      "BIN": 1036467,
      "BBL": 1013070023,
      "NTA": "MN19",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50066240,
      dba: "KO SUSHI",
      boro: "Manhattan",
      building: 1329,
      street: "2 AVENUE",
      zipcode: 10021,
      phone: 2124391678,
      cuisine_description: "Japanese",
      inspection_date: "05/12/2022",
      action: "Violations were cited in the following area(s).",
      violation_code: "02B",
      violation_description: "Hot food item not held at or above 140º F.",
      critical_flag: "Critical",
      score: 22,
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "Cycle Inspection / Initial Inspection",
      "Latitude": 40.7675858,
      "Longitude": -73.95926326,
      "Community Board": 108,
      "Council District": 4,
      "Census Tract": 12600,
      "BIN": 1072227,
      "BBL": 1014257501,
      "NTA": "MN31",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50131931,
      dba: "Cotra",
      boro: "Brooklyn",
      building: 451,
      street: "CARROLL STREET",
      zipcode: 11215,
      phone: 8189849439,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.67745692,
      "Longitude": -73.98727712,
      "Community Board": 306,
      "Council District": 39,
      "Census Tract": 11900,
      "BIN": 3007508,
      "BBL": 3004470050,
      "NTA": "BK37",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50143383,
      dba: "",
      boro: "Manhattan",
      building: 41,
      street: "KENMARE STREET",
      zipcode: 10012,
      phone: 19173459305,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.72076729,
      "Longitude": -73.99537868,
      "Community Board": 102,
      "Council District": 1,
      "Census Tract": 4100,
      "BIN": 1007158,
      "BBL": 1004790005,
      "NTA": "MN24",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    },
    {
      camis: 50143003,
      dba: "MAYER BROWN",
      boro: "Manhattan",
      building: 1221,
      street: "AVENUE OF THE AMERICAS",
      zipcode: 10036,
      phone: 7043285184,
      cuisine_description: "",
      inspection_date: "01/01/1900",
      action: "",
      violation_code: "",
      violation_description: "",
      critical_flag: "Not Applicable",
      score: "",
      grade: "",
      grade_date: "",
      record_date: "11/25/2023",
      inspection_type: "",
      "Latitude": 40.75909387,
      "Longitude": -73.98213574,
      "Community Board": 105,
      "Council District": 4,
      "Census Tract": 12500,
      "BIN": 1022693,
      "BBL": 1010010029,
      "NTA": "MN17",
      "Location Point1": "",
      "Zip Codes": "",
      "Community Districts": "",
      "Borough Boundaries": "",
      "City Council Districts": "",
      "Police Precincts": ""
    }
  ];
